### ISSUE TITLE
Error saving to file

### ISSUE THREAD

**Issue by eversonl** [krissrex/google-authenticator-exporter#6]
Hi, great script! really helpful. 
Not a major issue but I am having issues when trying to save to file 
```

`prompt: saveToFile:  y
prompt: filename:  lee.json
lee.json
true
Saving to "lee.json"...
node:internal/readline/emitKeypressEvents:71
            throw err;
            ^

TypeError: saveToFile is not a function
    at toJson (D:\py\gauth\src\index.js:120:5)
    at D:\py\gauth\src\index.js:181:9
    at D:\py\gauth\node_modules\prompt\lib\prompt.js:357:32
    at D:\py\gauth\node_modules\async\lib\async.js:154:25
    at assembler (D:\py\gauth\node_modules\prompt\lib\prompt.js:354:9)
    at D:\py\gauth\node_modules\prompt\lib\prompt.js:363:32
    at D:\py\gauth\node_modules\prompt\lib\prompt.js:658:5
    at Interface.onLine (D:\py\gauth\node_modules\read\lib\read.js:111:5)
    at Interface.emit (node:events:390:28)
    at Interface._onLine (node:readline:487:10)`
```
```

**Comment by eversonl** [comment]
I have no idea if I am right, but again it works for me today
to resolve this I changed the function name at line 64
from 
`function saveToFile(filename, data) {`
to 
`function saveToFile2(filename, data) {`

and at line 119 (ish) 
from
 ```
if (saveToFile && filename) {
    console.log(`Saving to "${filename}"...`);
    saveToFile(filename, JSON.stringify(accounts, undefined, 4));
  }

```
to 

 ```
if (saveToFile && filename) {
    console.log(`Saving to "${filename}"...`);
    saveToFile2(filename, JSON.stringify(accounts, undefined, 4));
  }
```

**Comment by krissrex** [comment]
Thanks for the issue. It was introduced in https://github.com/krissrex/google-authenticator-exporter/commit/395866e589ba05dfe31d3df34a563521b81732ef 
by shadowing the `saveToFile` function with the parameter.

It should now be fixed, by #8 :)
